<?php
class MyMemberExtension extends DataExtension
{
    public function updateCMSFields(FieldList $fields)
    {
        parent::updateCMSFields($fields); // TODO: Change the autogenerated stub
    }

    private static $db = [
        'MobilePhone'   => 'Varchar(15)',
        'BirthDate'     => 'Date',
        'Subscription'  => 'Boolean',
        'Active'        => 'Boolean',
        'Token'         => 'Varchar(200)',
        'TokenExpire'   => 'Date',

    ];
    private static $has_one = [];
    private static $many_many = [];
    private static $belongs_many_many = [];

    public function validate(ValidationResult $validationResult)
    {
        if ($this->owner->MobilePhone === '000')
        {
            $validationResult->error('Bad Mobile Phone.');

        }
        return $validationResult;
    }
}