// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  angular.module('sorted').directive('saveTrigger', [
    'Profile', '$analytics', function(Profile, $analytics) {
      return {
        restricted: 'A',
        link: function(scope, element) {
          var throwLoginWindow;
          throwLoginWindow = function() {
            return Profile.get(true).then(function(profile) {
              if (_.isEmpty(profile)) {
                angular.element('#login-modal').modal('show');
              } else {
                angular.element('#save-as-modal').modal('show');
              }
            });
          };
          return element.click(function() {
              $analytics.eventTrack('calculator', { category:'save', action: 'calculator'});
            if (sessionStorage.getItem('userData') === null) {
              sessionStorage.setItem('triggerSave', 'true');
            }
            throwLoginWindow();
          });
        }
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=saveTrigger.js.map
