// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  angular.module('sorted').filter('toTrusted', [
    '$sce', function($sce) {
      return function(text) {
        return $sce.trustAsHtml(text);
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=toTrusted.js.map
