---
# tasks file for php

- name: Install dependent repository
  apt: name=python-apt state=present

- name: Add PHP-FPM repo
  apt_repository: repo='ppa:ondrej/php5'

- name: Update apt cache
  apt: update_cache=yes

# Install php modules #######
- apt: name=php5-mcrypt
- apt: name=php5-cli
- apt: name=php5-mysql
- apt: name=php5-imagick
- apt: name=php5-fpm
- apt: name=php5-curl
- apt: name=php5-gd
- apt: name=imagemagick
- apt: name=curl
#############################
## Replace php.ini
#- name: Replace php.ini file
#  template: src=php.ini.j2 dest=/etc/php5/fpm/php.ini backup=yes

# Install composer
- name: Composer installation
  become_user: root
  shell: curl -sS https://getcomposer.org/installer | php -- --filename=composer --install-dir=/usr/local/bin