// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  angular.module('sorted').directive('socials', [
    'siteConfig', '$location', function(siteConfig, $location) {
      return {
        restricted: 'E',
        templateUrl: siteConfig.APP_PATH + "app/components/socials/socials.html",
        scope: {
          data: '='
        },
        link: function(scope) {
          scope.siteConfig = siteConfig;
          scope.url = $location.absUrl();
          scope.$watch('data', function(data) {
            if (void 0 === data.ThumbnailImage.Filename) {
              data.ThumbnailImage.Filename = data.CalcIcon.Filename;
            }
            scope.fbUrl = 'https://www.facebook.com/sharer/sharer.php?u=' + 'https://' + $location.host() + data.Link;
          });
          return $('.fb-share').click(function(e) {
            e.preventDefault();
            window.FB.ui({
              method: 'feed',
              name: scope.data.Title,
              link: scope.url,
              picture: 'https://' + $location.host() + '/' + scope.data.ThumbnailImage.Filename,
              caption: scope.url,
              description: scope.data.MetaDescription,
              message: ''
            });
            return false;
          });
        }
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=socials.js.map
