// Generated by CoffeeScript 1.9.3
$(document).ready(function() {

  var sliderContainer = $('.slider-list');
  var rotateLeft = function(){
    sliderContainer.append($('.slide').first())
  };
  var rotateRight =  function(){
    sliderContainer.prepend($('.slide').last())
  };

  $('#left').on('click', rotateRight)
  $('#right').on('click',rotateLeft)





  $('#menu-button').on('click', function(){
    $(this).toggleClass('active');
    $('.mobile-navigation-list').toggleClass('active');
  })



});
